
#Dependencias
FROM node:22-alpine as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install






#Builder - Construye la app
FROM node:22-alpine as build

WORKDIR /usr/src/app

#Copiar de deps, los modulos de Node
COPY --from=deps /usr/src/app/node_modules ./node_modules


# Copiar todo el codigo fuente de la aplicacion
COPY . .


RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force




# Crear la imagen final de Docker
FROM node:22-alpine as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

#Copiar carpeta de dist
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production

USER node

EXPOSE 3003

CMD [ "node","dist/main.js" ]
